import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-index',
  templateUrl: './index.component.html',
  styleUrls: ['./index.component.scss']
})
export class IndexComponent implements OnInit {

  selectedSloganList: string[] = [];

  ngOnInit(): void {
    /**
     * Generated By ChatGPT
     */
    let indexSloganList = [
      'Recording Learning Notes, Transmitting Technical Insights.',
      'Exploring The Endless Possibilities Of Technology To Turn Imagination Into Reality.',
      'Capturing The Journey Of Technical Discovery, One Note At A Time.',
      'Technical Notes That Reveal The Beauty Of The Digital World.',
      'The Art Of Note-Taking: Exploring The Intricacies Of Technology.',
      'Elevate My Technical Capabilities With The Power Of Note-Taking.',
      'Mastering The Intricacies Of Technology With Every Note.',
      'One Note, One Insight: Exploring The World Of Technology.',
      'Discovering The Depth Of Technology Through The Power Of Note-Taking.',
      'Elevating Technical Understanding Through The Art Of Note-Taking.',
      'Unlocking The Secrets Of Technology With The Power Of Note-Taking.'
    ];

    this.selectedSloganList = this.getRandomArrayElements(indexSloganList, 3);
  }

  /**
   * 随机从数组中取若干个值
   * 
   * @param arr 源数组
   * @param count 待取值个数
   * @returns 目标值组成的数组
   */
  private getRandomArrayElements(arr: string[], count: number) {
    let myArray = arr.slice();
    let i = myArray.length;
    let startIndex = i - count;
    while(i > startIndex) {
      i--;
      let randomNum = Math.floor((i + 1) * Math.random());
      let temp = myArray[randomNum];
      myArray[randomNum] = myArray[i];
      myArray[i] = temp;
    }
    return myArray.slice(startIndex);
  }



}
