name: Node CD

on:
  release:
    types: [created]
  workflow_dispatch:


jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: banwagon-linux
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Npm Build
        run: npm run build --if-present
      - name: Copy dist to production
        uses: garygrossgarten/github-action-scp@release
        with: 
          local: dist/a-blog-system-front/
          remote: ${{ vars.DEPLOY_FILE_PATH }}
          host: ${{ secrets.BANWAGON_VM_HOST }}
          port: ${{ secrets.BANWAGON_VM_PORT }}
          username: ${{ secrets.BANWAGON_VM_USERNAME }}
          password: ${{ secrets.BANWAGON_VM_PASSWORD }}
      
